//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptaxation.GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FullName {
            get {
                return ((string)(this["FullName"]));
            }
            set {
                this["FullName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PersonalIdentificationNumber {
            get {
                return ((string)(this["PersonalIdentificationNumber"]));
            }
            set {
                this["PersonalIdentificationNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProcessName {
            get
            {
                string processName = ((string) (this["ProcessName"]));
                if (string.IsNullOrWhiteSpace(processName))
                {
                    processName = "Acrord32.exe";
                }
                return processName;
            }
            set {
                this["ProcessName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TransactionsPath {
            get {
                return ((string)(this["TransactionsPath"]));
            }
            set {
                this["TransactionsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FiatRatesPath {
            get {
                string fiatRatesPath = ((string)(this["FiatRatesPath"]));
                if (string.IsNullOrWhiteSpace(fiatRatesPath))
                {
                    fiatRatesPath = System.AppDomain.CurrentDomain.BaseDirectory + @"Resources\Rates\Riksbanken rates 2014-01-02 to 2020-03-28.csv";
                }
                return fiatRatesPath;
            }
            set {
                this["FiatRatesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CryptoToFiatRatesPath {
            get {
                string cryptoToFiatRatesPath = ((string)(this["CryptoToFiatRatesPath"]));
                if (string.IsNullOrWhiteSpace(cryptoToFiatRatesPath))
                {
                    cryptoToFiatRatesPath = System.AppDomain.CurrentDomain.BaseDirectory + @"Resources\Rates\Bitstamp BTC price data 2010-07-31 to 2019-02-08.csv";
                }
                return cryptoToFiatRatesPath;
            }
            set {
                this["CryptoToFiatRatesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputPath {
            get {
                return ((string)(this["OutputPath"]));
            }
            set {
                this["OutputPath"] = value;
            }
        }
    }
}
